#theme: jekyll-theme-cayman
name: Jose Villalobos
email: jorovipe@gmail.com
linkedin_username: ""
github_username: jorovipe97
twitter_username: gamebite10


markdown: kramdown
# Build settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
highlighter: rouge
