#theme: jekyll-theme-cayman
name: Jose Villalobos
short: I am Jose #Short description
large: Graphic and web developer, I don`t happy until you become happy. #Large description
# No estoy feliz hasta que el problema por el cual me contrataste este bien solucionado.

# Location
city: Medellin
state: Antioquia
country: Colombia

# Social networks
email: jorovipe@gmail.com
linkedin_username: ""
github_username: jorovipe97
twitter_username: gamebite10
facebook_username: ""
gplus_username: ""


# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
    # Use GitHub flavored markdown, including triple backtick fenced code blocks
    input: GFM
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        # Use existing pygments syntax highlighting css
        css_class: 'highlight'
